CREATE TABLE IF NOT EXISTS chat_user_presence (
    username VARCHAR(100) PRIMARY KEY,
    last_seen TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    is_online BOOLEAN DEFAULT FALSE,
    typing_to VARCHAR(100) DEFAULT NULL
);
